# Generated by Django 5.0.2 on 2024-02-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_student_remove_user_created_at_remove_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='username',
        ),
    ]
